### PR TITLE
Customizable actions

### PR DESCRIPTION
**Pull request by jaulz**
"successAction", "errorAction", "abortAction" in configuration will allow the user to customize the actions that are triggered

### CODE REVIEW

**Comment by jaulz** [comment]
By the way: great library that accelerates my developments a lot :-)

**Comment by klis87** [comment]
@jaulz thanks, nice idea, why not :) And I am glad you find this library useful, and... stay tuned, soon it will be even better! I will merge your PR during weekend, 1 question though, I guess changing successAction", "errorAction", or "abortAction" would require proper adjustments in `requestsReducer` to keep them in sync, right?

**Comment by klis87** [comment]
Exactly :) Will be possible but I guess we will need to add this note to readme.

I am curious, you will definitely won't use reducers or you might consider using them in the future? I am asking as a feedback, because I will add new features to reducer in the near future, and I might made it more user friendly if necessery.

**Comment by jaulz** [comment]
Currently, I don't use them because I work with ImmutableJS structures and partly have some special requirements (e.g. merging instead of overwriting). For the cause of consistency I will stick to this pattern but let's see which features you will implement and maybe they will convince me :-) 

However, what I noticed is that the naming is not really consistent with reducers and sagas. For sagas you call the properties "success", "error" and "abort". For reducers you call it "getSuccessAction", "getErrorAction" and "getAbortAction". I think we should decide for one and the same naming.

One last thing: I think about implementing a check that happens immediately before the request. The reason is that I would like to prevent the request if the user is offline (or any other check based on the current state) and instead trigger another action (e.g. SHOW_MESSAGE). Any idea how to implement it best? Maybe a very long `delay` in onRequest?

**Comment by klis87** [comment]
@jaulz Thanks again for you PR, I made some comments, generally I think we should allow to modify how `meta` is structured if structured at all in all actions.

You are right, I think that in reducers `getSuccessAction` in `requestReducer` should be named as `success` to make it consistent.

> One last thing: I think about implementing a check that happens immediately before the request.

Please raise a separate issue so this could be useful for other people.

**Comment by jaulz** [comment]
Great, I will once I have investigated more :-)
Could you please merge the pull request in the meantime or do you need anything else?

**Comment by klis87** [comment]
@jaulz I dont want to merge it and publish as not finished not to confuse users with constant api changes. I could do those changes myself, but unfortunately I am really busy recently so I dont have time to do it :(

If you dont have time as well, you could always publish your fork to NPM for now, until this PR is merged here

**Comment by jaulz** [comment]
No worries, that's fine for me. Though I'm excited to see the new reducer functions :-)

**Comment by klis87** [comment]
Merged, stay tuned for new reducers :)

**Pull request merged**
