### PR TITLE
Close #244, add promise driver

### LINKED ISSUE #244: Could we also support promises?
I really enjoy using this library and I feel like we could also use it for promises?

(FSA) Payload would look something like:
```
{
  payload: {
    promise: new Promise(...),
  }
}
```

### PR DESCRIPTION
**Pull request by strdr4605**
@klis87 waiting for comments

### CODE REVIEW

**Comment by klis87** [comment]
@strdr4605 Thx! looks very nice!

I am thinking about 2 things now:
1) do you have any ideas how we could support aborts? like in axios or fetch driver? does your promise library you use has abort support? Because of course axios promise is just example, this driver should be used for APIs libraries, this is your use case right?
2) how to distinguish between queries and mutations, I guess the only way would be to use `meta.asMutation: true` and by default promise requests would be queries?

**Comment by strdr4605** [comment]
1. Don't know how to do it here. For example, facades used in our app make requests with Axios but we don't use abort (as I know).
2. I did not think about this (as I used `redux-saga-requests` only for GET requests and with my custom reducer). Probably `meta.asMutation: true` is the only way by now.

**Comment by klis87** [comment]
@strdr4605 I am worried about 1) because on another branch https://github.com/klis87/redux-saga-requests/blob/removing-sagas/packages/redux-saga-requests-axios/src/axios-driver.js#L12 I solved aborts without sagas just on promises in the link you can see. A special error REQUEST_ABORTED is thrown and it is listened here https://github.com/klis87/redux-saga-requests/blob/removing-sagas/packages/redux-saga-requests/src/middleware/create-send-requests-middleware.js#L127

The issue is that saga version allows to dispatch ABORT actions even for drivers not supporting aborts, but current implementation in version without saga cannot do this.

I would really like to support aborts even for drivers which dont abort requests. Those are faking aborts, but benefit is still there, namely you prevent race condition bugs, even if a request is not cancelled, its response will be ignored when abort action is dispatched instead of success one.

I am starting to believe this cannot really be done with drivers as promises, maybe we should use zen-observable...

I ignored this issue as all drivers supported aborts anyway, but with promise driver i think it won't be possible. 

Unless you have any ideas how to achieve that?

**Comment by strdr4605** [comment]
By looking at this example: https://medium.com/@bramus/cancel-a-javascript-promise-with-abortcontroller-3540cbbda0a9

I added abort support for any promise and successfully tested it (_ABORT action is dispatched)

**Comment by klis87** [comment]
very interesting!

I was going to suggest sth different, namely:
```js
export const promiseDriver = () => requestConfig => {
  let aborted = false;

  const responsePromise = requestConfig.promise
    .then(response => {
      if (aborted) {
        throw 'REQUEST_ABORTED';
      }

      return { data: response };
    })
    .catch(error => {
      if (aborted) {
        throw 'REQUEST_ABORTED';
      }

      throw error;
    });

  responsePromise.cancel = () => {
    aborted = true;
  };

  return responsePromise;
};
```

I guess this should work too. I will need to think about it and test both solutions. But on the 1st glance your solution is much better because in your case promise will be rejected with `REQUEST_ABORTED` when responsePromise.cancel is called immediately, while in my case it will just wait for normal promise resolve/reject and throw this error when aborted flag is true. Because of this I like your solution much more.

I would like to finish removing sagas first before merging this, is that ok?

With newest version you can easily use your promise driver by passing `isRequestAction` to `handleRequests` so that request.promise will be treated as request action like you did in this PR

**Pull request merged**
